export const SEARCH_USERNAME = 'SEARCH_USERNAME';
export const SEARCH_USERNAME_SUCCESS = 'SEARCH_USERNAME_SUCCESS';
export const SEARCH_USERNAME_ERROR = 'SEARCH_USERNAME_ERROR';
export const SEARCH_USERNAME_URL = 'GET /search/users';
export const FETCH_USER_REPOSITORY = 'FETCH_USER_REPOSITORY';
export const FETCH_USER_REPOSITORY_SUCCESS = 'FETCH_USER_REPOSITORY_SUCCESS';
export const FETCH_USER_REPOSITORY_ERROR = 'FETCH_USER_REPOSITORY_ERROR';
export const FETCH_USER_REPOSITORY_URL = 'GET /users/'